<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pokdex</name>
   <tag></tag>
   <elementGuidId>7b64527b-71a5-43b1-8a7b-63eb69292213</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.title.title_pokeball</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bac31204-d388-409f-a342-dc7916bec938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title title_pokeball</value>
      <webElementGuid>a58f0fc7-543a-42ef-a4c3-225409764a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pokédex</value>
      <webElementGuid>23d88615-d880-4474-af85-d985c77e45cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths adownload cssscrollbar cors no-overflowscrolling cookies fullscreen no-nintendo todataurljpeg todataurlwebp&quot;]/body[@class=&quot;us fluid custom-form-elements&quot;]/nav[@class=&quot;main&quot;]/div[@class=&quot;content-wrapper&quot;]/ul[1]/li[@class=&quot;explore&quot;]/a[1]/span[@class=&quot;title title_pokeball&quot;]</value>
      <webElementGuid>2b14b865-1d7d-42ec-9f5e-a2bc71240100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::span[3]</value>
      <webElementGuid>f1581b58-63cd-46de-abf0-f0a7cbd9907e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/following::span[6]</value>
      <webElementGuid>f2f9c928-e17a-47b2-a25e-168ed5066f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Games &amp; Apps'])[1]/preceding::span[3]</value>
      <webElementGuid>455f1a19-0ed0-40b4-87ec-25748e2417e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trading Card Game'])[1]/preceding::span[6]</value>
      <webElementGuid>4a7a631e-de95-43c3-a0d1-65790204ca57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pokédex']/parent::*</value>
      <webElementGuid>e850f81a-17df-43ac-9bf9-88f331abc885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span[3]</value>
      <webElementGuid>925274fc-f5db-4562-a138-74aca6fe366c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pokédex' or . = 'Pokédex')]</value>
      <webElementGuid>b571315a-261d-4bae-b59d-b4b661011256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
